name: Docker Build and Push
on: workflow_dispatch
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::135263545391:role/githubactions
          role-session-name: samplerolesession
          aws-region: "ap-south-1"
      # Upload a file to AWS s3
      - name: Copy backend to s3
        run: |
          aws s3 cp backend s3://vijay.0430  

